services:
  watchtower:
    image: containrrr/watchtower
    container_name: onkyo-api-watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - DOCKER_CONFIG=/
  onkyo-api:
    image: ghcr.io/mtyszkiewicz/onkyo-api
    container_name: onkyo-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "0.0.0.0:8001:8080"
