services:
  onkyo-api:
    image: ghcr.io/mtyszkiewicz/onkyo-api:latest
    container_name: onkyo-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "0.0.0.0:8001:8080"
