version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  onkyo-api:
    image: ghcr.io/mtyszkiewicz/onkyo-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: onkyo-api
    ports:
      - "0.0.0.0:8001:8080"