name: Go

on:
  push:
    branches:
      - 'main'
    # paths:
    #   - 'onkyo-api/**'

permissions:
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./onkyo-ctl
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Build
        run: go build -v ./cmd/api/main.go
        
      - name: Test with the Go CLI
        run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./onkyo-ctl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./onkyo-ctl
          push: true
          tags: |
            ghcr.io/mtyszkiewicz/onkyo-api:${{ env.COMMIT_SHORT_SHA }}
            ghcr.io/mtyszkiewicz/onkyo-api:latest